#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 20 11:04:45 2017

@author: emg
"""

from gensim import corpora, models
import pickle

month_docs = pickle.load(open('/Users/emg/Programmming/GitHub/the_donald_project/tidy_data/monthly_comments.p','rb'))    

freq = corpora.Dictionary.load('/tmp/td_dictionary.dict')
freq.filter_extremes(no_below=0, no_above=1.0, keep_n=1000)

top_words = freq.token2id.keys()

texts = [[word for word in document.lower().split() if word not in top_words]
        for document in month_docs]



from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.parsing.preprocessing import STOPWORDS

vectorizer = TfidfVectorizer(max_features=1000,stop_words=STOPWORDS)
train_vectors = vectorizer.fit_transform(month_docs)



corpus = corpora.MmCorpus('/tmp/td_corpus.mm') # should be n months in length
tfidf = models.TfidfModel(corpus) # step 1 -- initialize a model
corpus_tfidf = tfidf[corpus]

lsi = models.LsiModel.load('/Users/emg/Programmming/GitHub/the_donald_project/analysis_results/td_lsi', mmap='r')
    